apiVersion: crema/v1
kind: CremaConfig
spec:
  scaledObjects:
    - spec:
        scaleTargetRef:
          name: projects/${project_id}/locations/${region}/workerpools/${worker_pool_name}
        minReplicaCount: 0 # Optional. Default: 0
        maxReplicaCount: 100 # Optional. Default: 100
        triggers: # See https://keda.sh/docs/2.17/scalers/
          - type: rabbitmq
            metadata:
              host: amqp://${user}:${password}@${host}:5672/
              protocol: amqp
              mode: QueueLength # QueueLength or MessageRate
              value: "100.50" # message backlog or publish/sec. target per instance
              activationValue: "10.5" # Optional. Activation threshold
              queueName: ${queue}
        advanced: # Optional
          horizontalPodAutoscalerConfig:
            behavior:
              scaleDown:
                stabilizationWindowSeconds: 60
                policies:
                  - type: Pods
                    value: 2
                    periodSeconds: 10
              scaleUp:
                stabilizationWindowSeconds: 60
                policies:
                  - type: Pods
                    value: 10
                    periodSeconds: 10
  pollingInterval: 30 # Optional. Seconds